---
- import_playbook: install_docker.yml

- name: Run Jenkins
  hosts: dev
  tasks:
    - name: Download Image
      docker_image:
        name: 'jenkins/jenkins:lts'
        state: present

    - name: Run
      docker_container:
        name: jenkins
        image: 'jenkins/jenkins:lts'
        published_ports: 8080:8080, 50000:50000
      

