---
- name: VMWare
  hosts: all
  tasks:
    - name: Gather facts about a single vm
      vmware_guest_facts: 
        name: vm_name
        hostname: host
        datacenter: ha-datacenter
        validate_certs: no
