---
- name: VMWare
  hosts: all
  tasks:
    - name: Gather facts about a single vm
      vmware_guest_facts: 
        name: vm_name
        hostname: vm_host
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter: ha-datacenter
        validate_certs: no
