---
- name: VMWare
  hosts: all
  tasks:
    - name: Gather facts about a single vm
      vmware_guest_facts: 
        name: 'cvt c rafi at1'
        hostname: 192.168.1.31
        username: "{{ lookup('env', 'VMWARE_USER') }}"
        password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        datacenter: ha-datacenter
        validate_certs: no
