---
- name: VMWare
  hosts: all
  tasks:
    - name: Gather facts about a single vm
      vmware_guest_facts: 
        hostname: host
        name: name
        username: rafi
        password: password
        datacenter: 
          delegate_to: localhost
          register: facts
